name: lint_python
on: [push, pull_request] 
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - run: pip install flake8
      - run: flake8 . --count --max-line-length=88 --show-source --statistics
